# Generated by Django 3.0.2 on 2020-05-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rentalcar_car_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalcar',
            name='car_name',
        ),
    ]
